### ISSUE TITLE
Consider shx REPL

### ISSUE THREAD

**Issue by levithomason** [shelljs/shx#12]
Was toying with a thin streaming wrapper around the `shx` function. Would be cool to give this some thought.  There is good potential to create a cross platform shell repl:

![shx repl](http://g.recordit.co/n5q3iq4OAT.gif)

This also raised some issues with how we are accepting argv in `shx` and parsing them in parseArgs.  I'll wait until we get some of the other more fundamental issues/PRs cleared before digging in more.

Leaving this issue here as food for thought, for now.

**Comment by nfischer** [comment]
Would this have any benefit over dthree/cash?

**Comment by levithomason** [comment]
Not sure, i'm not completely familiar with their work.  This was just so easy to do it seemed like it was worth considering:

```js
#!/usr/bin/env node
const shx = require('./lib/shx');

const PROMPT = 'shx› ';

process.stdout.write(PROMPT);

process.stdin.on('data', data => {
  // arg parsing in shx is awkward,
  const argv = ['', ''].concat(data.toString().replace(/\n$/g, '').split(' '));
  shx(argv);
  process.stdout.write(`\n${PROMPT}`)
});
```

I'll take a closer look at cash later and see what the extra benefits would be, if any.

**Comment by nfischer** [comment]
If this is simple enough to get right, I'm fine with this. It seems like an awesome feature!

It seems similar to a project we were thinking of starting, which would be a node REPL that includes the latest version of ShellJS already required (globally), so commands like `cp()` are immediately available (if there's any interest in helping with that as well). It might be nice to have a coffee script REPL too, since it's a bit easier to type that stuff out (it'd be more shell-like).

**Comment by ariporad** [comment]
I think that we should just defer this to cash, which is more complete.

**Comment by levithomason** [comment]
Agreed for now, given bandwidth constraints and the scope of this add.
