### ISSUE TITLE
wildcards not working on mv

### ISSUE THREAD

**Issue by AaronNGray** [shelljs/shx#149]
The following is not working :- 

    shx mv test/*.js test/*.mjs

getting the following error :-

    mv: dest is not a directory (too many sources)

**Comment by nfischer** [comment]
This is expected behavior, so I'll close this (but I'm happy to answer further questions).

---

Unix and Windows handle glob (wildcard) expansion differently. I think this [blog post](https://blogs.msdn.microsoft.com/dancre/2005/05/15/the-difference-in-wildcard-expansion-between-windows-and-unixmacintosh/) has a pretty good explanation. TL;DR Unix shells expand globs before launching the command, Windows shells don't (the program must expand globs itself).

If you're running your command on unix, you're seeing unix expansion at play (and `shx` can't turn that off). If you're running on Windows, `shx` intentionally emulates unix expansion for consistent behavior across the platforms.

---

In your specific case, I recommend writing a for-loop:

```sh
for file in test/*.js; do
  shx mv "$file" "test/${file%.js}.mjs"
done
```

Or, use shelljs to make it cross-platform:

```js
shell.ls('test/*.js').forEach(file => {
  shell.mv(file, file.replace(/\.js$/, '.mjs'));
});
```
