### ISSUE TITLE
Recursive globbing (./**/) works differently depending on OS

### ISSUE THREAD

**Issue by leonheess** [shelljs/shx#190]
Consider this command: `shx cp -r ./src/**/*.js .`. It is copying all `.js`-files from `./src` and its sub-directories  into `.`. On Windows 10 it will also consider every `.js`-file inside `src` but on Debian it will only copy files from sub-directories of `src` but not `src` itself.

Windows 10:
```
src/
├── sub-dir/
│   ├── will-be-copied.js
├── will-also-be-copied.js
```

Debian:
```
src/
├── sub-dir/
│   ├── will-be-copied.js
├── will-NOT-be-copied.js
```

**Comment by nfischer** [comment]
What is the behavior of `shx cp -r "./src/**/*.js" .` (glob is wrapped in quotes)? Is that the same on both operating systems?

**Comment by leonheess** [comment]
> What is the behavior of `shx cp -r "./src/**/*.js" .` (glob is wrapped in quotes)? Is that the same on both operating systems?

No, also different

**Comment by nfischer** [comment]
> but on Debian it will only copy files from sub-directories of src but not src itself.

I cannot reproduce this on my Ubuntu machine:

```shell
$ mkdir src
$ touch src/1.js
$ shx cp -r ./src/**/*.js .
$ ls
1.js  src
```

I think this is more likely a problem with the shell on your Debian machine. Maybe you have a really old version of Bash shell which doesn't support the `**` syntax? I'm also not sure what you mean by "Only happens if it's called with npm or yarn" but if you're talking about `npm`'s ["package scripts"](https://docs.npmjs.com/cli/v8/using-npm/scripts) feature, then this may also point to the same problem because that uses the system's `/bin/sh` shell ([source](https://manpages.debian.org/experimental/npm/npm-run-script.1.en.html#:~:text=By%20default%2C%20on%20Unix%2Dlike%20systems%20it%20is%20the%20/bin/sh%20command)).

Regardless, this seems unlikely to be a problem with `shx` or `shelljs`. Unix shells perform glob-expansion **before** invoking the command. This means that by the time `shx` is invoked, the shell has already decided the full list of matching files and provided those explicitly to our process (in your example, this looks like `shx cp -r ./src/sub-dir/will-be-copied.js ./src/will-NOT-be-copied.js`).

You can work around this by forcing your shell to **not** perform glob-expansion, which will allow `shx` to perform the expansion itself. In the commandline this looks like`shx cp -r "./src/**/*.js" .` (note the placement of the double-quote characters). In `package.json` this looks like:

```json
{
  "scripts": {
    "name-of-script": "shx cp -r \"./src/**/*.js\" ."
  }
}
```

**Comment by leonheess** [comment]
Not sure what to tell you. I have a npm package script that is `shx cp -r ./src/**/*.js .` and if I run in on my Windows machine it does something different than it does in the Ubuntu Azure pipeline (as described in the issue description).

I had to rewrite to `shx cp -r ./src/*.js . && shx cp -r ./src/sub-dir/*.js .` for it to work identical on both machines.

**Comment by nfischer** [comment]
> Not sure what to tell you. I have a npm package script that is `shx cp -r ./src/**/*.js .`

I believe you have that script, but did you see my recommended workaround about wrapping the glob expansion in double quote characters (`"`)?
