### ISSUE TITLE
Switch to Mocha

### ISSUE THREAD

**Issue by nfischer** [shelljs/shx#22]
Reopening this, since it looks like one of our other issues got closed. I looked into test frameworks a bit more.

 - ava seems awesome, but I'm concerned with its concurrent nature. I'd imagine our tests involve modifying state on disk, so concurrently running tests each modifying disk state could be a big issue. If ava has a good workaround for this (other than the `.serial` method for every test case, which sounds like a pain), feel free to correct me.
 - mocha is pretty popular, and runs things concurrently. That's a bit slower than ava since it's not in parallel, but should be more than fast enough.
 - [rocha](https://github.com/bahmutov/rocha) seems pretty promising. This is a wrapper on top of mocha (so it's still running tests concurrently), but it runs them in a random order (this makes sure we don't have a dependency between different test cases). If we get a random order that fails, rocha will keep that order until we get the tests to pass (so it's still easy to debug issues). If we're starting from scratch, it should be easy to write tests that don't depend on order.

I don't care too much which framework we use, as long as it works and ties into coverage tools. I'm mostly posting this as a reminder that we need some sort of unit tests.

**Comment by levithomason** [comment]
I setup tests a few weeks back in #14.  This was done with Ava per some earlier conversations we had.  We we're waiting for @ariporad to push some more tests but it sounds like they got lost.

Glad you brought this up though, when setting up Ava I had the same concerns.  I also had more tests included with the initial setup but they were giving me troubles due to the concurrent nature of things.

There were other awkward things too, like [`before/after hooks`](https://github.com/sindresorhus/ava#before--after-hooks) only applying to tests in the file that they are in.  So you can't have global utils with life cycle hooks unless you concat all your tests?

For instance I like to have a single sinon sandbox util that I can import into my tests.  The sandbox includes it's own `afterEach( ...restore)` hook.  This was I can create spies/stubs/mocks at will at know that the cleanup is done.  Another one, a console util for silencing the console for a single test `consoleUtil.disableOnce()`, this util needs an `afterEach()` hook as well.

All that said, I'd love to switch to mocha, [sinon](http://sinonjs.org/), [chai](http://chaijs.com/), [sinon-chai](https://github.com/domenic/sinon-chai), [dirty-chai](https://github.com/prodatakey/dirty-chai) for the testing rig.

**Comment by ariporad** [comment]
I personally vote rocha, it looks very cool
On Fri, Apr 8, 2016 at 7:21 PM, Nate Fischer <notifications@github.com> wrote:
Reopening this, since it looks like one of our other issues got closed. I looked into test frameworks a bit more.

 * ava seems awesome, but I'm concerned with its concurrent nature. I'd imagine our tests involve modifying state on disk, so concurrently running tests each modifying disk state could be a big issue. If ava has a good workaround for this (other than the .serial method for every test case, which sounds like a pain), feel free to correct me.
 * mocha is pretty popular, and runs things concurrently. That's a bit slower than ava since it's not in parallel, but should be more than fast enough.
 * rocha [https://github.com/bahmutov/rocha] seems pretty promising. This is a wrapper on top of mocha (so it's still running tests concurrently), but it runs them in a random order (this makes sure we don't have a dependency between different test cases). If we get a random order that fails, rocha will keep that order until we get the tests to pass (so it's still easy to debug issues). If we're starting from scratch, it should be easy to write tests that don't depend on order.

I don't care too much which framework we use, as long as it works and ties into coverage tools. I'm mostly posting this as a reminder that we need some sort of unit tests.

**Comment by levithomason** [comment]
Of the two, I'd prefer not using rocha.  It is not well maintained and [doesn't support `--compilers`](https://github.com/bahmutov/rocha/issues/7).  I'd be concerned about what other issues it would bring. I think we can avoid cross test dependencies without this.

I say we start with mocha, if we want, we can always drop `rocha` on top since it is just a wrapper.

**Comment by nfischer** [comment]
SGTM. @levithomason do you want to handle switching the test framework?

**Comment by levithomason** [comment]
Sure thing

**Comment by nfischer** [comment]
This blocks #23

**Comment by levithomason** [comment]
thanks for the bump, will put some time to this tonight.

**Comment by levithomason** [comment]
PR up #31
