### ISSUE TITLE
shx with no args: help message?

### ISSUE THREAD

**Issue by backspaces** [shelljs/shx#48]
An upgrade request: if I run shx with no args (ls, pwd, etc), it would make sense to print out some sort of help messages. List the available commands?

**Comment by nfischer** [comment]
Good suggestion! We might want to investigate adding an explicit `shx help` command as well. Perhaps `shx` with no args would suggest running `shx help` to see available commands.

Thanks for trying out the project!

**Comment by backspaces** [comment]
Thanks back at you, this is a life saver for me! I've written more bash
than any other language I think. Sun made all of us be build masters for a
couple of months, sorta hazing I guess. I use bash daily, and now I'll use
shx daily.

**Comment by levithomason** [comment]
This is a great suggestion. @nfischer I'd like to consider `yargs` as we think more about rounding out the cli.

**Comment by ariporad** [comment]
I'd actually vote against `yargs`, because we don't actually want to parse most CLI arguments.
I'll submit a `shx help` PR.
On Thu, May 5, 2016 at 9:36 AM, Levi Thomason <notifications@github.com> wrote:
This is a great suggestion. @nfischer [https://github.com/nfischer] I'd like to consider yargs as we think more about rounding out the cli.

**Comment by levithomason** [comment]
Update, `shx help` is merged and released in `v0.1.2`.  You'll see help when missing a command or using an invalid command.  There is also a prompt to run help if you use an unsupported command.

@backspaces I believe this covers all the needs.  Please reopen if we've missed anything.  Thanks!
