### ISSUE TITLE
Code coverage badge seems to show for latest (passing) PR, not for master branch

### ISSUE THREAD

**Issue by nfischer** [shelljs/shx#51]
It appears that the code coverage badge shows for the latest PR (that passes CI), not for the latest master branch. I noticed that the badge went up to 84% **before merging** the last PR. Currently, the latest passing PR and master branch have the same coverage, but this could probably be tested out by creating a fake PR that deletes the tests (0% coverage) and then I believe the badge icon will change.

Fixing this is probably as simple as changing a URL in the README badge.

**Comment by levithomason** [comment]
Bade is already pointed at master:
```
[![Codecov](https://img.shields.io/codecov/c/github/shelljs/shx/master.svg?style=flat-square&label=coverage)](https://codecov.io/gh/shelljs/shx)
```
[![Codecov](https://img.shields.io/codecov/c/github/shelljs/shx/master.svg?style=flat-square&label=coverage)](https://codecov.io/gh/shelljs/shx)


Also, as seen here I believe the master branch is at 84% per codecov at least:
https://codecov.io/gh/shelljs/shx/branch/master

This makes sense since the last merged PR should have the exact same head as the last merged PR.  Closing based on this, feel free to re-open if there are further issues.

**Comment by nfischer** [comment]
Posting here to mark down that, as discovered by #52, this is still an issue. This appears to be a problem with codecov (see codecov/support#191), so we can leave this issue closed here.

**Comment by levithomason** [comment]
Awesome, thanks for finding the related codecov issue!
