### ISSUE TITLE
Globbing arguments to an external command

### ISSUE THREAD

**Issue by cvrebert** [shelljs/shx#68]
One annoying difference between Windows' old shell and the Unix shell is the lack of globbing on Windows. shx already addresses this for shell builtins and coreutils by including globbing logic in each of the commands' implementations, but this still leaves external commands that weren't written with Windows in mind (and thus don't implement their own globbing) out in the cold.
Would you be open to a PR that adds a feature which simply globs all its arguments and runs the result?
For example, `shx XXX foo *` would be equivalent to `foo *` in a Unix shell.
As for naming, [`command`](https://www.gnu.org/software/bash/manual/html_node/Bash-Builtins.html#index-command) (like the bash builtin) might be an option. Or `glob`. Or whatever; I'm not picky about the name.

**Comment by nfischer** [comment]
If I'm understanding things correctly, a command like `shx rm *.txt` should work as expected, since the underlying ShellJS `shell.rm()` function will perform any glob expansion that the external shell itself hasn't already done. Correct me if this is not the case.

Would this be for other commands, such as `git`? Those currently are not supported under `shx` (We'd prefer you run `$ git add foo.txt` instead of trying `$ shx exec git add foo.txt`).

**Comment by cvrebert** [comment]
> Would this be for other commands, such as git?

Yes. (Although I don't know if `git` in particular is affected, but let's pretend/assume it is for the sake of example.)
While `$ git add foo.txt` of course works, something like `$ git add *.txt` doesn't.

**Comment by levithomason** [comment]
Would it not make sense to simply extend `exec` to handle globs?  So that this works on windows:

```
$ shx exec git add *.txt
```

**Comment by cvrebert** [comment]
I'd be equally fine with that. Since [`exec`](https://github.com/shelljs/shx/blob/aa925e211fb3993572a6be4bd0eff95d350177ee/src/config.js#L14) is on the blacklist, I wasn't sure that was an option.

**Comment by levithomason** [comment]
It currently is, I am thinking it may be handy to allow `exec` to handle cross platform tasks (like globs) so that it can be used on the ShellJS side as well as here in `shx`.

/cc @arturadib

**Comment by levithomason** [comment]
Whoops, /cc @ariporad I mean.

**Comment by nfischer** [comment]
The reason I wanted exec to be on the blacklist is to nudge people toward running commands like `$ cmd -f arg` instead of `$ shx exec cmd -f arg`. This keeps people away from all the exec nastiness, since there's very little that it brings to the table for shx. There's no technical reason it couldn't be removed from the blacklist.

Right now shelljs exec doesn't actually perform any of its own globing, it still defers to the shell. We have been thinking of ways to rework exec to make it suit the community's needs better.

I'll have some time today, so I'll try to write something up on the shelljs side and see if it's worth pursuing.

**Comment by cvrebert** [comment]
@nfischer Any luck with your write-up?
Also, I'm more than willing to make PRs related to this.

**Comment by nfischer** [comment]
Just got back from a vacation. I'll see if I can implement something tomorrow for ShellJS using `execFile` under the hood, and see how that works out.

**Comment by nfischer** [comment]
I opened up shelljs/shelljs#495 for this, and should have a fix out soon. If someone is feeling especially ambitious, feel free to take it up.

**Comment by nfischer** [comment]
I probably won't have the time to fix up that ShellJS issue, but if anyone else wants to take it up, feel free.

**Comment by nfischer** [comment]
Merging into #65 (the fix for both is to use `shell.cmd()` when it's finished).
